Arqtech/Controllers/LojaController.cs
using Arqtech.Data;
using Arqtech.Models;
using Arqtech.Repositorio;
using Arqtech.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Arqtech.Controllers
{
    public class LojaController : Controller
    {
        private readonly LojaRepositorio _lojaRepositorio;

        public LojaController(LojaRepositorio lojaRepositorio)
        {
            _lojaRepositorio = lojaRepositorio;
        }

        public async Task<IActionResult> IndexLoja()
        {
            var lojas = await _lojaRepositorio.BuscaTodasLojas();
            return View(lojas);
        }

        [HttpGet]
        public IActionResult CriaLoja()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriaLoja(CriaLojaViewModel criaLojaViewModel)
        {
            if (criaLojaViewModel is null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var loja = new LojaModel
                {
                    Nome = criaLojaViewModel.Nome,
                    Cidade = criaLojaViewModel.Cidade,
                    Descricao = criaLojaViewModel.Descricao,
                    Numero = criaLojaViewModel.Numero,
                    Logradouro = criaLojaViewModel.Logradouro,
                };

                var lojaCriada = await _lojaRepositorio.CriaLoja(loja);

                if (lojaCriada)
                {
                    return RedirectToAction("IndexLoja");
                }
            }

            return View(criaLojaViewModel);
        }

        public async Task<IActionResult> DeletarLoja(int lojaId)
        {
            if (lojaId == 0)
            {
                return NotFound();
            }

            var lojaEncontrada = await _lojaRepositorio.BuscaLojaPorId(lojaId);

            if (lojaEncontrada is not null)
            {
                await _lojaRepositorio.DeletaLoja(lojaEncontrada.LojaId);
                return RedirectToAction("IndexLoja");
            }

            return View(lojaEncontrada);
        }

        public async Task<IActionResult> EditarLoja(int lojaId)
        {
            if (lojaId == 0)
            {
                return NotFound();
            }

            var loja = await _lojaRepositorio.BuscaLojaPorId(lojaId);

            if (loja == null)
            {
                return NotFound();
            }

            return View(loja);
        }

        [HttpPost]
        public async Task<IActionResult> SalvarEdicaoLoja(LojaModel lojaModel)
        {
            await _lojaRepositorio.AtualizaLoja(lojaModel);
            return RedirectToAction("IndexLoja");
        }
    }
}

Arqtech/Controllers/ProjetoController.cs
using Arqtech.Models;
using Arqtech.Repositorio;
using Arqtech.ViewModels;
using iText.Html2pdf;
using iText.Kernel.Pdf;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Execution;
using Microsoft.CodeAnalysis;

namespace Arqtech.Controllers
{
    public class ProjetoController : Controller
    {
        private readonly ProjetoRepositorio _projetoRepositorio;
        private readonly UserManager<UsuarioModel> _userManager;
        private readonly MaterialRepositorio _materialRepositorio;

        public ProjetoController(ProjetoRepositorio projetoRepositorio, UserManager<UsuarioModel> userManager, MaterialRepositorio materialRepositorio)
        {
            _projetoRepositorio = projetoRepositorio;
            _userManager = userManager;
            _materialRepositorio = materialRepositorio;
        }

        public async Task<IActionResult> IndexProjeto()
        {
            var usuario = await _userManager.GetUserAsync(User);

            if (usuario is not null)
            {
                if (User.IsInRole("Admin"))
                {
                    var projetos = await _projetoRepositorio.BuscaTodosProjetos();
                    return View(projetos);
                }
                else
                {
                    var projetos = await _projetoRepositorio.BuscaProjetosPorUsuario(usuario.Id);
                    return View(projetos);
                }
            }

            return View();
        }

        [HttpGet]
        public IActionResult CriaProjeto()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriaProjeto(CriaProjetoViewModel criaProjetoViewModel)
        {
            var usuario = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                if (usuario is not null)
                {
                    var projetoCriado = await _projetoRepositorio.CriaProjetoAsync(criaProjetoViewModel, usuario);

                    if (projetoCriado)
                    {
                        return RedirectToAction("IndexProjeto");
                    }
                }
                else
                {
                    ModelState.AddModelError("Usuário", "Usuário não encontrado!");
                }
            }

            return View(criaProjetoViewModel);
        }

        public async Task<IActionResult> DetalhesProjeto(int projetoId)
        {
            var projeto = await _projetoRepositorio.BuscaProjetoPorId(projetoId);

            if (projeto is null)
            {
                return NotFound();
            }

            ViewBag.Materiais = await _materialRepositorio.BuscaTodosMateriais();

            return View(projeto);
        }

        [HttpPost]
        public async Task<IActionResult> CriarListaMaterial([FromBody] List<CriaListaMaterialViewModel> itensMateriais)
        {
            var listaMaterias = new ListaMaterialModel
            {
                Materiais = new List<MaterialModel>()
            };

            double totalListaMaterial = 0;

            var projeto = await _projetoRepositorio.BuscaProjetoPorId(itensMateriais[0].ProjetoId);

            if (projeto is not null)
            {
                for (int i = 0; i < itensMateriais.Count; i++)
                {
                    double preco = itensMateriais[i].Preco;
                    int quantidade = itensMateriais[i].Quantidade;
                    totalListaMaterial += preco * quantidade;

                    var materialEncontrado = await _materialRepositorio.BuscaMaterialPorId(itensMateriais[i].MaterialId);

                    if (materialEncontrado is not null)
                    {
                        materialEncontrado.Quantidade = quantidade;
                        listaMaterias.Materiais.Add(materialEncontrado);
                    }
                }

                projeto.ListaMaterial = listaMaterias;
                projeto.ValorMaterial = totalListaMaterial;
                projeto.ValorTotalProjeto = projeto.ValorProjetoArquiteto + projeto.ValorPedreiro + projeto.ValorMaterial;

                await _projetoRepositorio.AtualizaProjeto(projeto);

                return RedirectToAction("DetalhesProjeto", new { projetoId = projeto.ProjetoId });
            }

            return RedirectToAction("IndexProjeto");
        }

        [HttpGet]
        public async Task<IActionResult> EditarProjeto(int projetoId)
        {
            var projeto = await _projetoRepositorio.BuscaProjetoPorId(projetoId);

            if (projeto is not null)
            {
                return View(projeto);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditarProjeto(ProjetoModel projeto)
        {
            var usuario = await _userManager.GetUserAsync(User);

            if (projeto is not null)
            {
                projeto.Usuario = usuario;
                projeto.UsuarioId = usuario.Id;
                await _projetoRepositorio.AtualizaProjeto(projeto);

                return RedirectToAction("IndexProjeto");
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> DeletarProjeto(int projetoId)
        {
            if (projetoId == 0)
            {
                return NotFound();
            }

            var projetoEncontrado = await _projetoRepositorio.BuscaProjetoPorId(projetoId);

            if (projetoEncontrado is not null)
            {
                await _projetoRepositorio.RemoveProjeto(projetoEncontrado);
                return RedirectToAction("IndexProjeto");
            }

            return View(projetoEncontrado);
        }

        [HttpPost]
        public async Task<IActionResult> UploadImagensProjeto(int projetoId, List<IFormFile> files)
        {
            if (files != null && files.Count > 0)
            {
                var projeto = await _projetoRepositorio.BuscaProjetoPorId(projetoId);
                if (projeto == null)
                {
                    return NotFound();
                }

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await file.CopyToAsync(memoryStream);
                            var fileBytes = memoryStream.ToArray();
                            var base64String = Convert.ToBase64String(fileBytes);
                            var imagemProjeto = new ImagemProjetoModel
                            {
                                Imagem = base64String,
                                ProjetoId = projetoId
                            };
                            await _projetoRepositorio.AdicionaImagemProjeto(imagemProjeto);
                        }
                    }
                }

                return RedirectToAction("DetalhesProjeto", new { ProjetoId = projetoId });
            }

            return BadRequest("Arquivo(s) inválido(s).");
        }


        [HttpPost]
        public async Task<IActionResult> UploadImagem(int projetoId, IFormFile file)
        {
            if (file != null && file.Length > 0)
            {
                var projeto = await _projetoRepositorio.BuscaProjetoPorId(projetoId);
                if (projeto == null)
                {
                    return NotFound();
                }

                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    var fileBytes = memoryStream.ToArray();
                    var base64String = Convert.ToBase64String(fileBytes);
                    projeto.ImagemCapa = base64String;
                }

                await _projetoRepositorio.AtualizaProjeto(projeto);

                return RedirectToAction("DetalhesProjeto", new { projetoId = projetoId });
            }

            return BadRequest("Arquivo inválido.");
        }

        public async Task<IActionResult> GerarPdfProjeto(int projetoId)
        {
            var projeto = await _projetoRepositorio.BuscaProjetoPorId(projetoId);

            if (projeto == null)
            {
                return NotFound();
            }

            var conteudoHtml = await _projetoRepositorio.RenderizarHtmlEstagio(projeto);
            var nomePdf = $"{projeto.ProjetoId}-.pdf";

            try
            {
                var memoryStream = new MemoryStream();
                var writer = new PdfWriter(memoryStream);
                var pdf = new PdfDocument(writer);
                var converter = new ConverterProperties();

                HtmlConverter.ConvertToPdf(conteudoHtml, pdf, converter);

                pdf.Close();

                return File(memoryStream.ToArray(), "application/pdf", nomePdf);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Erro ao gerar PDF: " + ex.Message);
                return RedirectToAction("IndexProjeto");
            }
        }
    }
}

Arqtech/Controllers/UsuarioController.cs
using Arqtech.Models;
using Arqtech.Repositorio;
using Arqtech.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Arqtech.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuarioRepositorio _usuarioRepositorio;
        private readonly UserManager<UsuarioModel> _userManager;
        private readonly SignInManager<UsuarioModel> _signInManager;

        public UsuarioController(UsuarioRepositorio usuarioRepositorio, UserManager<UsuarioModel> userManager, SignInManager<UsuarioModel> signInManager)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> IndexUsuario()
        {
            var usuarios = await _usuarioRepositorio.BuscaTodosUsuarios();
            return View(usuarios);
        }

        public async Task<IActionResult> DetalhesUsuario(string usuarioId)
        {
            if (usuarioId is null)
            {
                return NotFound();
            }
            else
            {
                var usuario = await _usuarioRepositorio.BuscaUsuarioPorId(usuarioId);

                if (usuario is not null)
                {
                    return View(usuario);
                }
                else
                {
                    return NotFound();
                }
            }
        }

        [HttpGet]
        public IActionResult CriaUsuario()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriaUsuario(CriaUsuarioViewModel criaUsuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                var usuarioCriado = await _usuarioRepositorio.CriaUsuario(criaUsuarioViewModel);

                if (usuarioCriado.Succeeded)
                {
                    return RedirectToAction("Login");
                }
                else
                {
                    ModelState.AddModelError("Registro", "Falha ao registrar usuário!");
                }
            }

            return View(criaUsuarioViewModel);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LogaUsuarioViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
                return View(loginViewModel);

            var user = await _userManager.FindByNameAsync(loginViewModel.Email);

            if (user is not null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, loginViewModel.Password, false, false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("Password", "Senha incorreta, tente novamente");
                }
            }
            else
            {
                ModelState.AddModelError("UserName", "Esse e-mail não está em nosso sistema");
            }

            return View(loginViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

Arqtech/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<UsuarioModel> signInManager;
@inject UserManager<UsuarioModel> userManager;
@{
    var user = await userManager.GetUserAsync(User);
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Arqtech</title>
    <link rel="stylesheet" href="~/assets/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/css/Spacelab.css" asp-append-version="true" />
	<link href="~/assets/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
	<link href="~/assets/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white">Arqtech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            @if (User.IsInRole("Admin") || User.IsInRole("Arquiteto") || User.IsInRole("Engenheiro"))
                            {
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Usuario" asp-action="IndexUsuario">Usuarios</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Material" asp-action="IndexMaterial">Materiais</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Loja" asp-action="IndexLoja">Lojas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Projeto" asp-action="IndexProjeto">Projetos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Agenda">Agenda</a>
                                </li>
                                <li class="nav-item d-flex justify-content-start">
                                    <form asp-area="" asp-controller="Usuario" asp-action="Logout" method="post" class="nav-link">
                                        <button type="submit" class="nav-link" style="background: none; border: none; padding: 0; margin:0 0 0 0.1em; cursor: pointer;">
                                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                                <i class="ni ni-button-power text-sm opacity-10" style="color: #00365d"></i>
                                            </div>
                                            <span class="nav-link-text ms-1">@user.Nome @user.Sobrenome</span>
                                        </button>
                                    </form>
                                </li>
                            }
                            else if (User.IsInRole("Cliente"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Projeto" asp-action="IndexProjeto">Projetos</a>
                                </li>
                                <li class="nav-item d-flex justify-content-start">
                                    <form asp-area="" asp-controller="Usuario" asp-action="Logout" method="post" class="nav-link">
                                        <button type="submit" class="nav-link" style="background: none; border: none; padding: 0; margin:0 0 0 0.1em; cursor: pointer;">
                                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                                <i class="ni ni-button-power text-sm opacity-10" style="color: #00365d"></i>
                                            </div>
                                            <span class="nav-link-text ms-1">@user.Nome @user.Sobrenome</span>
                                        </button>
                                    </form>
                                </li>
                            }

                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CriaUsuario">Registre-se</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="p-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row align-items-center" style="height: 60px;">
                @* <div class="col-md-3">
                    <h4 class="text-black">Entre em Contato</h4>
                    <p class="text-white">
                        Para mais informações sobre nossos serviços, entre em contato conosco:<br>
                        Email: <a class="text-white">contato@arqtech.com</a><br>
                        Telefone: (XX) XXXXX-XXXX
                    </p>
                </div> *@
                <div class="col-md-6 text-white d-flex align-items-center justify-content-end">
                    <a>&copy; 2024 - Desenvolvido por Caio Maestrello e Dhiego Arsuffi.</a>
                </div>
            </div>
        </div>
    </footer>

@*     <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-2 my-2 border-top ">
            <div class="col-md-6 d-flex align-items-center">
                <h3 class="text-black">Entre em Contato</h3>
                <p class="text-black">
                    Para mais informações sobre nossos serviços, entre em contato conosco:<br>
                    Email: <a class="text-black">contato@arqtech.com</a><br>
                    Telefone: (XX) XXXXX-XXXX
                </p>
            </div>
            <div class="col-md-6 text-black d-flex align-items-center justify-content-end">
                <a>&copy; Arqtech - Desenvolvido por Caio Maestrello e Dhiego Arsuffi</a>
            </div>
        </footer>
    </div> *@
    <script src="~/assets/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/lib/bootstrap/dist/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://fullcalendar.io/js/fullcalendar-2.2.5/fullcalendar.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>