Arqtech/ViewModels/CriaMaterialViewModel.cs
namespace Arqtech.ViewModels
{
    public class CriaMaterialViewModel
    {
        public string Nome { get; set; }
        public double Preco { get; set; }
        public string? Descricao { get; set; }
        public int LojaId { get; set; }
    }
}

Arqtech/Controllers/MaterialController.cs
using Arqtech.Models;
using Arqtech.Repositorio;
using Arqtech.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Arqtech.Controllers
{
    public class MaterialController : Controller
    {
        private readonly MaterialRepositorio _materialRepositorio;
        private readonly LojaRepositorio _lojaRepositorio;
        public MaterialController(MaterialRepositorio materialRepositorio, LojaRepositorio lojaRepositorio)
        {
            _materialRepositorio = materialRepositorio;
            _lojaRepositorio = lojaRepositorio;
        }

        public async Task<IActionResult> IndexMaterial()
        {
            var materiais = await _materialRepositorio.BuscaTodosMateriais();
            return View(materiais);
        }

        [HttpGet]
        public async Task<IActionResult> CriaMaterial()
        {
            ViewBag.Lojas = await _lojaRepositorio.BuscaTodasLojas();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriaMaterial(CriaMaterialViewModel criaMaterialViewModel)
        {
            if (ModelState.IsValid)
            {
                var materialCriado = await _materialRepositorio.CriaMaterial(criaMaterialViewModel);

                if (materialCriado)
                {
                    return RedirectToAction("IndexMaterial");
                }
            }

            return View(criaMaterialViewModel);
        }

        public async Task<IActionResult> DetalhesMaterial(int materialId)
        {
            if (materialId == 0)
            {
                return NotFound();
            }

            var material = await _materialRepositorio.BuscaMaterialPorId(materialId);

            if (material is not null)
            {
                return View(material);
            }

            return View(material);
        }

        public async Task<IActionResult> EditarMaterial(int materialId)
        {
            if (materialId == 0)
            {
                return NotFound();
            }

            var loja = await _materialRepositorio.BuscaMaterialPorId(materialId);

            if (loja == null)
            {
                return NotFound();
            }

            return View(loja);
        }

        [HttpPost]
        public async Task<IActionResult> SalvarEdicaoMaterial(MaterialModel materialModel)
        {
            var loja = await _lojaRepositorio.BuscaLojaPorId(materialModel.LojaId);

            if (loja is not null)
            {
                materialModel.Loja = loja;
                await _materialRepositorio.AtualizaMaterial(materialModel);
                return RedirectToAction("IndexMaterial");
            }

            return View(materialModel);
        }

        public async Task<IActionResult> DeletarMaterial(int materialId)
        {
            if (materialId == 0)
            {
                return NotFound();
            }

            var materialEncontrado = await _materialRepositorio.BuscaMaterialPorId(materialId);

            if (materialEncontrado is not null)
            {
                await _materialRepositorio.DeletaMaterial(materialEncontrado.MaterialId);
                return RedirectToAction("IndexMaterial");
            }

            return View(materialEncontrado);
        }
    }
}

Arqtech/Views/Material/CriaMaterial.cshtml
@model CriaMaterialViewModel

<div class="container mt-5">
    <h2>Cadastro de Material</h2>
    <form asp-controller="Material" asp-action="CriaMaterial" method="post">
        <div class="form-group">
            <label asp-for="Nome" class="control-label">Nome</label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Preco" class="form-label">Preço</label>
            <input asp-for="Preco" type="number" class="form-control" id="Preco" name="Preco" placeholder="Digite o preço do material">
            <span asp-validation-for="Preco" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Descricao" class="form-label">Descrição</label>
            <textarea class="form-control" id="Descricao" name="Descricao" rows="3" placeholder="Digite a descrição do material"></textarea>
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
        <h4 class="text-center mb-4">Selecionar Loja</h4>
        <div class="row mb-4">
            <div class="col">
                <select id="LojaId" name="LojaId" asp-for="LojaId" class="form-select">
                    @foreach (var lojas in ViewBag.Lojas)
                    {
                        <option value="@lojas.LojaId">@lojas.Nome</option>
                    }
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a asp-controller="Material" asp-action="IndexMaterial" class="btn btn-secondary m-1">Voltar para o cadastro</a>

    </form>
</div>

Arqtech/Views/Material/DetalhesMaterial.cshtml
@model MaterialModel

@{
    ViewData["Title"] = "Detalhes do Material";
}

<div class="container">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Detalhes do Material</h3>
    </div>
    <br />
    <div class="card-details">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-center">Material</h4>
                <br />
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th scope="row" class="col-sm-3">Id do Material:</th>
                            <td class="col-sm-9">@Model.MaterialId</td>
                        </tr>
                        <tr>
                            <th scope="row" class="col-sm-3">Nome:</th>
                            <td class="col-sm-9">@Model.Nome</td>
                        </tr>
                        <tr>
                            <th scope="row" class="col-sm-3">Preço:</th>
                            <td class="col-sm-9">@Model.Preco.ToString("C")</td>
                        </tr>
                        <tr>
                            <th scope="row" class="col-sm-3">Descrição:</th>
                            <td class="col-sm-9">@Model.Descricao</td>
                        </tr>
                        <tr>
                            <th scope="row" class="col-sm-3">ID da Loja:</th>
                            <td class="col-sm-9">@Model.LojaId</td>
                        </tr>
                    </tbody>
                </table>
                <div class="text-center mt-3">
                    <a asp-action="IndexMaterial" asp-controller="Material" class="btn btn-secondary">Voltar</a>
                    <a asp-action="EditarMaterial" asp-controller="Material" asp-route-MaterialId="@Model.MaterialId" class="btn btn-secondary">Editar</a>
                </div>
            </div>
        </div>
    </div>    
</div>

Arqtech/Views/Material/EditarMaterial.cshtml
@model MaterialModel

@{
    ViewData["Title"] = "Editar Material";
}

<div class="container">
    <div class="p-3 mb-3">
        <h3 class="text-left" style="color: white">Detalhes do Material</h3>
    </div>
    <br />
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Informações do Material</h4>
                    <form asp-controller="Material" asp-action="SalvarEdicaoMaterial" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="MaterialId" />
                        <input type="hidden" asp-for="LojaId" />
                        <input type="hidden" asp-for="Loja" />
                        <div class="row">
                            <div class="form-group">
                                <label asp-for="Nome" class="control-label">Nome:</label>
                                <input asp-for="Nome" class="form-control" />
                                <span asp-validation-for="Nome" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <label asp-for="Preco" class="control-label">Preço:</label>
                                <input asp-for="Preco" class="form-control" />
                                <span asp-validation-for="Preco" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <label asp-for="Descricao" class="control-label">Descrição:</label>
                                <input asp-for="Descricao" class="form-control" />
                                <span asp-validation-for="Descricao" class="text-danger"></span>
                            </div>
                        </div>
                        <br />
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary col-5">Salvar</button>
                            <a asp-controller="Material" asp-action="IndexMaterial" class="btn btn-secondary">Voltar para a Lista</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Arqtech/Views/Material/IndexMaterial.cshtml
@model List<MaterialModel>

@{
    ViewData["Title"] = "Materiais";
}

<div class="container">
    <div class="d-flex justify-content-between align-items-center p-3 mb-3">
        <h1>Materiais</h1>
        <a class="btn btn-success" asp-area="" asp-controller="Material" asp-action="CriaMaterial">Criar novo material</a>
    </div>
       
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th class="text-center text-black" scope="col">Nome</th>
                            <th class="text-center text-black" scope="col">Preço</th>
                            <th class="text-center text-black" scope="col">Descrição</th>
                            <th class="text-center text-black" scope="col">Loja</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var material in Model)
                        {
                            <tr>
                                <td class="text-center">@material.Nome</td>
                                <td class="text-center">@material.Preco.ToString("C2")</td>
                                <td class="text-center">@material.Descricao</td>
                                <td class="text-center">@material.Loja.Nome</td>
                                <td class="text-center">
                                    <div class="btn-group" role="group">
                            <a class="btn btn-primary rounded m-1" asp-controller="Material" asp-action="DetalhesMaterial" asp-route-MaterialId="@material.MaterialId"><i class="bi bi-eye"></i></a>
                            <a class="btn btn-danger rounded m-1" asp-controller="Material" asp-action="DeletarMaterial" asp-route-MaterialId="@material.MaterialId"><i class="bi bi-trash"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
</div>